// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ArchitectureSample.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AddCustomerFeature : object, Xunit.IClassFixture<AddCustomerFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AddCustomer.feature"
#line hidden
        
        public AddCustomerFeature(AddCustomerFeature.FixtureData fixtureData, ArchitectureSample_Tests_Features_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "AddCustomer", "\tIn order to add customer\r\n\tAs a user\r\n\tI want to be able add customer", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Add new customer")]
        [Xunit.TraitAttribute("FeatureTitle", "AddCustomer")]
        [Xunit.TraitAttribute("Description", "Add new customer")]
        [Xunit.TraitAttribute("Category", "Customers")]
        [Xunit.InlineDataAttribute("Payman", "Tatar", "1976/09/09", "+31647675034", "Paymantatar@gmail.com", "1234567890", "Saved", new string[0])]
        [Xunit.InlineDataAttribute("Payman", "Tatar", "1976/09/09", "+9896860", "Paymantatar@gmail.com", "1234567890", "Not Saved", new string[0])]
        [Xunit.InlineDataAttribute("Payman", "Tatar", "1976/09/09", "+31647675034", "Payman.Tatar.com", "1234567890", "Not Saved", new string[0])]
        [Xunit.InlineDataAttribute("Payman", "Tatar", "1893/08/03", "+31647675034", "Paymantatar@gmail.com", "1234567890", "Not Saved", new string[0])]
        [Xunit.InlineDataAttribute("Payman", "Tatar", "1976/09/09", "+31647675034", "Paymantatar@gmail.com", "127890", "Not Saved", new string[0])]
        public void AddNewCustomer(string firstName, string lastName, string birthOfDate, string phoneNumber, string email, string bankAccount, string expectation, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Customers"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("FirstName", firstName);
            argumentsOfScenario.Add("LastName", lastName);
            argumentsOfScenario.Add("BirthOfDate", birthOfDate);
            argumentsOfScenario.Add("PhoneNumber", phoneNumber);
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("BankAccount", bankAccount);
            argumentsOfScenario.Add("Expectation", expectation);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add new customer", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "FirstName",
                            "LastName",
                            "BirthOfDate",
                            "PhoneNumber",
                            "Email",
                            "BankAccount"});
                table1.AddRow(new string[] {
                            string.Format("{0}", firstName),
                            string.Format("{0}", lastName),
                            string.Format("{0}", birthOfDate),
                            string.Format("{0}", phoneNumber),
                            string.Format("{0}", email),
                            string.Format("{0}", bankAccount)});
#line 8
 testRunner.Given("I have entered the customer details", ((string)(null)), table1, "Given ");
#line hidden
#line 11
 testRunner.When("I save the customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
 testRunner.Then(string.Format("the customer details should be {0}", expectation), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AddCustomerFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AddCustomerFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
