global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - PrometheusInstance:9090
 - job_name: node
   static_configs:
    - targets:
       - NodeExporterInstance:9100
 - job_name: Api
   static_configs:
    - targets:
       - WebApi:3030