apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: blazorserver
  name: blazorserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blazorserver
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/architecturesample-architecturesamplenetwork: "true"
        io.kompose.service: blazorserver
    spec:
      containers:
        - image: architecturesample/blazor/server:dev
          name: architecturesample-blazorserver
          ports:
            - containerPort: 4848
              hostPort: 9091
              protocol: TCP
      restartPolicy: Always
