apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: blazorclient
  name: blazorclient
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blazorclient
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/architecturesample-architecturesamplenetwork: "true"
        io.kompose.service: blazorclient
    spec:
      containers:
        - image: architecturesample/blazor/client:dev
          name: architecturesample-blazorclient
          ports:
            - containerPort: 80
              hostPort: 9191
              protocol: TCP
      restartPolicy: Always
