apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.network/architecturesample-architecturesamplenetwork: "true"
    io.kompose.service: grafanainstance
  name: grafanainstance
spec:
  containers:
    - env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin@321
      image: grafana/grafana:latest
      name: architecturesample-grafana
      ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
      volumeMounts:
        - mountPath: /etc/grafana/provisioning
          name: grafanainstance-claim0
  restartPolicy: OnFailure
  volumes:
    - name: grafanainstance-claim0
      persistentVolumeClaim:
        claimName: grafanainstance-claim0
