apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: nodeexporterinstance
  name: nodeexporterinstance
spec:
  ports:
    - name: "5454"
      port: 5454
      targetPort: 9100
  selector:
    io.kompose.service: nodeexporterinstance
