apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.network/architecturesample-architecturesamplenetwork: "true"
    io.kompose.service: prometheusinstance
  name: prometheusinstance
spec:
  containers:
    - image: prom/prometheus
      name: architecturesample-prometheus
      ports:
        - containerPort: 9090
          hostPort: 2390
          protocol: TCP
      volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheusinstance-claim0
  restartPolicy: OnFailure
  volumes:
    - name: prometheusinstance-claim0
      persistentVolumeClaim:
        claimName: prometheusinstance-claim0
